from dynaconf import Validator
from pathlib import Path

VALIDATORS = [
    # General
    Validator("GENERAL__DEVICE_ID", default=None),
    Validator("GENERAL__DEBUG", default=False, cast=bool),
    Validator("GENERAL__LOG_LEVEL", default="info"),  # error, warning, info, debug
    # Display
    Validator(
        "DISPLAY__CANVAS__WIDTH",
        default=768,
        cast=int,
    ),
    Validator(
        "DISPLAY__CANVAS__HEIGHT",
        default=64,
        cast=int,
    ),
    # MQTT
    Validator(
        "MQTT__HOST",
        required=True,
        cast=str,
    ),
    Validator(
        "MQTT__PORT",
        default=1883,
        cast=int,
    ),
    Validator(
        "MQTT__TOPIC_PREFIX__APP",
        default="wideboy",
        cast=str,
    ),
    Validator(
        "MQTT__TOPIC_PREFIX__HOMEASSISTANT__DEFAULT",
        default="homeassistant",
        cast=str,
    ),
    Validator(
        "MQTT__TOPIC_PREFIX__HOMEASSISTANT__STATESTREAM",
        default="homeassistant/statestream",
        cast=str,
    ),
    Validator(
        "MQTT__USER",
        default=None,
        cast=str,
    ),
    Validator(
        "MQTT__PASSWORD",
        default=None,
        cast=str,
    ),
    Validator(
        "MQTT__KEEPALIVE",
        default=60,
        cast=int,
    ),
    Validator(
        "MQTT__LOG_MESSAGES",
        default=False,
        cast=bool,
    ),
    # PATHS
    Validator(
        "PATHS__IMAGES_ICONS",
        default="images/icons",
        cast=Path,
    ),
    Validator(
        "PATHS__IMAGES_BACKGROUNDS",
        default="images/backgrounds",
        cast=Path,
    ),
    Validator(
        "PATHS__IMAGES_WEATHER",
        default="images/weather",
        cast=Path,
    ),
    Validator("PATHS__IMAGES_SCREENSHOTS", default="images/screenshots", cast=Path),
    # LED DISPLAY MATRIX
    Validator(
        "DISPLAY__MATRIX__ENABLED",
        default=False,
        cast=bool,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__GPIO_MAPPING",
        default="regular",
        cast=str,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__ROWS",
        default=64,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__COLS",
        default=256,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__CHAIN",
        default=1,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__PARALLEL",
        default=3,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__MULTIPLEXING",
        default=0,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__PIXEL_MAPPER",
        default="V-mapper",
        cast=str,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__PWM_BITS",
        default=8,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__BRIGHTNESS",
        default=50,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__SCAN_MODE",
        default=0,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__ROW_ADDR_TYPE",
        default=0,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__SHOW_REFRESH",
        default=False,
        cast=bool,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__LIMIT_REFRESH",
        default=None,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__INVERSE",
        default=False,
        cast=bool,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__RGB_SEQUENCE",
        default="RGB",
        cast=str,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__PWM_LSB_NANOSECONDS",
        default=200,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__PWM_DITHER_BITS",
        default=0,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__NO_HARDWARE_PULSE",
        default=False,
        cast=bool,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__PANEL_TYPE",
        default=None,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__SLOWDOWN_GPIO",
        default=4,
        cast=int,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__DAEMON",
        default=False,
        cast=bool,
    ),
    Validator(
        "DISPLAY__MATRIX__DRIVER__NO_DROP_PRIVS",
        default=True,
        cast=bool,
    ),
]
