import pygame


class AppMetadata:
    NAME = "wideboy"
    TITLE = "WideBoy"
    DESCRIPTION = "WideBoy RGB Matrix Platform"
    VERSION = "0.0.1"
    AUTHOR = "JingleManSweep"
    REPO_URL = "https://github.com/jinglemansweep/wideboy"


DYNACONF_ENVVAR_PREFIX = "WIDEBOY"

EVENT_MASTER_POWER = pygame.USEREVENT + 11
EVENT_MASTER_BRIGHTNESS = pygame.USEREVENT + 12

EVENT_SCENE_NEXT = pygame.USEREVENT + 21
EVENT_NOTIFICATION_RECEIVED = pygame.USEREVENT + 22
EVENT_BUTTON_A = pygame.USEREVENT + 23
EVENT_BUTTON_B = pygame.USEREVENT + 24
EVENT_BUTTON_X = pygame.USEREVENT + 25
EVENT_BUTTON_Y = pygame.USEREVENT + 26
EVENT_BUTTON_L = pygame.USEREVENT + 27
EVENT_BUTTON_R = pygame.USEREVENT + 28
EVENT_BUTTON_DPAD_LEFT = pygame.USEREVENT + 29
EVENT_BUTTON_DPAD_RIGHT = pygame.USEREVENT + 30
EVENT_BUTTON_DPAD_UP = pygame.USEREVENT + 31
EVENT_BUTTON_DPAD_DOWN = pygame.USEREVENT + 32

EVENT_EPOCH_SECOND = pygame.USEREVENT + 51
EVENT_EPOCH_MINUTE = pygame.USEREVENT + 52
EVENT_EPOCH_HOUR = pygame.USEREVENT + 53

EVENT_MQTT_MESSAGE = pygame.USEREVENT + 61
EVENT_HASS_COMMAND = pygame.USEREVENT + 62
