import pygame


class AppMetadata:
    NAME = "wideboy"
    TITLE = "WideBoy"
    DESCRIPTION = "WideBoy RGB Matrix Platform"
    VERSION = "0.0.1"
    AUTHOR = "JingleManSweep"
    REPO_URL = "https://github.com/jinglemansweep/wideboy"


DYNACONF_ENVVAR_PREFIX = "WIDEBOY"

DEFAULT_POWER = True
DEFAULT_BRIGHTNESS = 128

EVENT_MASTER = pygame.USEREVENT + 11
EVENT_SCENE_MANAGER_NEXT = pygame.USEREVENT + 21
EVENT_SCENE_MANAGER_SELECT = pygame.USEREVENT + 22
EVENT_NOTIFICATION_RECEIVED = pygame.USEREVENT + 23
EVENT_ACTION_A = pygame.USEREVENT + 24
EVENT_ACTION_B = pygame.USEREVENT + 25
EVENT_NIGHT_MODE = pygame.USEREVENT + 26
EVENT_SCREENSHOT = pygame.USEREVENT + 31
EVENT_TIMER_SECOND = pygame.USEREVENT + 51
EVENT_EPOCH_SECOND = pygame.USEREVENT + 52
EVENT_EPOCH_MINUTE = pygame.USEREVENT + 53
EVENT_EPOCH_HOUR = pygame.USEREVENT + 54
EVENT_MQTT_MESSAGE_RECEIVED = pygame.USEREVENT + 61
EVENT_MQTT_MESSAGE_SEND = pygame.USEREVENT + 62
EVENT_HASS_ENTITY_UPDATE = pygame.USEREVENT + 71
EVENT_HASS_STATESTREAM_UPDATE = pygame.USEREVENT + 72

# GAMEPAD

# Stadia Controller
# 0: A, 1: B, 2: X, 3: Y, 4: LB, 5: RB, 6: LT, 7: RT, 8: Back, 9: Start, 10: L3, 11: R3, 12: Dpad Up, 13: Dpad Down, 14: Dpad Left, 15: Dpad Right


GAMEPAD = dict(
    BUTTON_A=0,
    BUTTON_B=1,
    BUTTON_X=2,
    BUTTON_Y=3,
    BUTTON_L=4,
    BUTTON_R=5,
)
