from enum import Enum

FPS_MAX = 100
FPS_CORR = 24 / FPS_MAX


class EventTypes(Enum):
    EVENT_PYGAME_INTERNAL = "EVENT_PYGAME_INTERNAL"
    EVENT_DEBUG_LOG = "EVENT_DEBUG_LOG"
    EVENT_CLOCK_NEW_SECOND = "EVENT_CLOCK_NEW_SECOND"
    EVENT_CLOCK_NEW_MINUTE = "EVENT_CLOCK_NEW_MINUTE"
    EVENT_CLOCK_NEW_HOUR = "EVENT_CLOCK_NEW_HOUR"
    EVENT_HASS_ENTITY_UPDATE = "EVENT_HASS_ENTITY_UPDATE"
