from pygame import USEREVENT

FPS_MAX = 100
FPS_CORR = 24 / FPS_MAX


EVENT_CLOCK_NEW_SECOND = USEREVENT + 11
EVENT_CLOCK_NEW_MINUTE = USEREVENT + 12
EVENT_CLOCK_NEW_HOUR = USEREVENT + 13
EVENT_HASS_ENTITY_UPDATE = USEREVENT + 21
