services:
  wideboy:
    image: ghcr.io/jinglemansweep/wideboy:latest
    restart: always
    privileged: true
    user: root
    devices:
      - /dev/mem:/dev/mem
    volumes:
      - /mnt/nas/media/images/artyfarty:/external/images/backgrounds:ro
    env_file:
      - ./docker.local.env     
