name: flake8

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          python -m venv ./venv
          . ./venv/bin/activate
          poetry install
      - name: flake8 check
        run: |
          . ./venv/bin/activate
          flake8 wideboy/
